### ISSUE TITLE
3.2.2 hyperlink update

### ISSUE THREAD

**Issue by millermc38** [mstrimas/ebird-best-practices#11]
Not a coding issue, but I think the hyperlink in chapter 3.2.2 is supposed to go to this page:
https://lpdaac.usgs.gov/products/mcd12q1v006/

I'm using eBird for my master's thesis (statistics), and this guide has been super helpful given that spacial packages have a bit of a steep learning curve. Thanks!

**Comment by mstrimas** [comment]
thanks for catching this! should be fixed now
