### ISSUE TITLE
Recommendation for Habitat Prep Setction

### ISSUE THREAD

**Issue by aeiche01** [mstrimas/ebird-best-practices#12]
I thought of a recommendation for the landcover covariates section: in it, you mention that it can act as a template for how to prepare all sorts of data (elevation, etc) but I've been having a devil of a time trying to figure out how to include BOTH the modis data and elevation data as environmental variables. It would be great to get a short section on how to prep the data so that the encounter models/occupancy models/abundance models include multiple types of environmental variables in one go. Would that be possible?

**Comment by mstrimas** [comment]
This is a great idea, and something I've been thinking about myself. I intend to add a section about bringing in elevation as a covariate, I've just been totally swamped with other things. Hopefully I'll have a chance to get to in sometime in September. Thanks!

**Comment by mstrimas** [comment]
Thanks again for the suggestion, the updated Chapter 3 now shows how to include elevation as an additional covariate

**Comment by aeiche01** [comment]
That's wonderful! I'm excited to give the new code a try. I'll keep trying to see if I can come up with new ideas that might help improve the book even further. Thank you!
