### ISSUE TITLE
Potential Plotting Improvement

### ISSUE THREAD

**Issue by millermc38** [mstrimas/ebird-best-practices#15]
Matt,

I'm slowly getting acclimated to the complexities of working with spatial data, so if my suggestion below overlooks some of the benefits of plot() and spatial data, you can go ahead and just close this out.

 I for one find plot() and its associated syntax tough to work with, and most users coming to this invaluable guide are probably more familiar with ggplot. To that end, building off of your code, I made the following function to project coordinates from a dataframe into regularly spaced points that geom_raster can handle. There's probably a more direct way to accomplish this, and I tried a few, but this is the only one I could come up with that would work:

df_to_GGraster_center_points<-function(input_df,crs,variable_to_plot_QUOTED){
  raster_for_plot <- input_df %>% 
    select(latitude,longitude,variable_to_plot_QUOTED)%>%
    # convert to sf
    st_as_sf(coords = c("longitude", "latitude"), crs = crs) %>% 
    st_transform(crs = projection(r)) %>% 
    # rasterize points
    rasterize(r) %>% 
    # project to albers equal-area for mapping
    projectRaster(crs = st_crs(102003)$proj4string, method = "ngb") %>% 
    # trim off empty edges of raster
    trim()%>%
    as.data.frame(xy = TRUE)%>%
    mutate(latitude=x,longitude=y)%>%
    na.omit()
}

From here, the data is plotted quickly with something like the below, and then customizing the output is easier in my view: 

ggplot()+
geom_raster(data = raster_for_plot, aes(x = latitude, y = longitude, fill = variable_to_plot_QUOTED)) 

Additionally, I've made a sort of custom template at the start of my script to handle things like color, labels, scale, font, etc, so plotting can simply be done with:

my_ebird_theme+
geom_raster(data = raster_for_plot, aes(x = latitude, y = longitude, fill = variable_to_plot_QUOTED)) 

Anyways, I thought I would share an initial plot plot from Wisconsin's Atlas. Model needs more work, but I love the viridis themes. Thanks to the team for this amazing resource!
![distribution](https://user-images.githubusercontent.com/22758569/72627280-30ddda00-391a-11ea-9de0-408d83377523.png)

**Comment by mstrimas** [comment]
Hi, thanks for the suggestion! I'm a huge fan of ggplot2 and use it for all plotting *except* when working with spatial data. Basically I feel when I'm making a map I want the finer grained control that base plotting allows. That said, I may be sacrificing ease of use if favor of aesthetics, so I will look into a ggplot approach.

As a side note, I've just moved this repo away from my personal website over to the official lab of ornithology account, so you'll want to use this repo from now on (https://github.com/CornellLabofOrnithology/ebird-best-practices) and update your links to the book to: https://cornelllabofornithology.github.io/ebird-best-practices/

**Comment by millermc38** [comment]
Very good, thanks for your thoughts!
