### ISSUE TITLE
MODIS Data Download

### ISSUE THREAD

**Issue by mpalumbo56** [mstrimas/ebird-best-practices#2]
A couple days ago I was able to download the MODIS tiles needed to work through example in the Best Practices for Wood Thrush in BCR 27. I attempted to go through that process again for a different area and received the following error message:

Error in (function (x, ...)  : 
  Make sure either 'wget' or 'curl' is available in order to download data from LP DAAC or NSIDC.

I also tried to re-download the tiles for the Wood Thrush in BCR 27 and receive the same error message. An excerpt of the code and output is: 

# earliest year of ebird data
> begin_year <- format(min(ebird$observation_date), "%Y.01.01")
> # end date for ebird data, mcd12q1 only exists up to 2017
> end_year <- min(format(max(ebird$observation_date), "%Y.12.31"), 
+                 "2017.12.31")
> # download tiles and combine into a single raster for each year
> tifs <- runGdal(product = "MCD12Q1", collection = "006", SDSstring = "01", 
+                 tileH = tiles@tileH, tileV = tiles@tileV,
+                 begin = begin_year, end = end_year, 
+                 outDirPath = "data", job = "modis") %>% 
+   pluck("MCD12Q1.006") %>% 
+   unlist()
########################
outProj          =  asIn 
pixelSize        =  asIn 
resamplingType   =  near 
Output Directory =  H:/EBird/data/data/data/modis 
########################
Local structure is up-to-date. Using offline information!
Error in (function (x, ...)  : 
  Make sure either 'wget' or 'curl' is available in order to download data from LP DAAC or NSIDC.

Any advice would be greatly appreciated.

**Comment by mstrimas** [comment]
What operating system are you on? MODIS is a tricky package to get set up, but it's odd that it downloaded fine the first time, then not when you ran it again. Did anything change in terms of your setup?

This section of the book is very much in development, we're trying to get the instructions working for a variety of systems, but it seems that slightly different system configurations can lead to the MODIS package not working. Thanks for your feedback, it'll help us improve this section!

**Comment by mpalumbo56** [comment]
Hi,
Thanks for the quick feedback. I am using Windows 7. 

I have tried to change the download method to wget and curl, but I can't tell if it is helping as the program continues to run for an extended period of time. I will try to re-install  OSGeo4W, in case I accidentally changed something.

**Comment by mpalumbo56** [comment]
I may have been mistaken with whether or not I was able to get it to run the first time. I may have used the already processed data that was provided in the tutorial. But the re-install of  OSGeo4W, did not change anything. I fully understand that this section is under development, but if you think of anything, any suggestions would be greatly appreciated. Would using a different source of land cover data be less "tricky"? 

 Thanks for all of work that is being put into this great resource,  I look forward to using it more.

**Comment by mstrimas** [comment]
Looking at the docs for MODIS package, I'm seeing that wget or curl is required for downloading data. These don't come with Windows by default. Try installing Cygwin (https://www.cygwin.com/), restart R, then try downloading again. Please let me know if it works so I can add that to the book.

**Comment by mpalumbo56** [comment]
I had cygwin installed on my computer originally but also tried to remove it and reinstall, but I still get the same error message. During the re-install I noticed that wget had status of "skip", So I re-installed and designated the installation to "keep" wget and I believe it is there but I still get the same error 
![Cygwin_wget](https://user-images.githubusercontent.com/48997059/55164541-34616400-5142-11e9-968c-6f7ac70df14a.JPG)

Do you think it would matter if my computer is administrator status or not? I recently had to change the status to download the programs.

**Comment by mstrimas** [comment]
Hmmm, I'm not sure what's going on here. I have access to a Windows computer and everything seems to work fine there. I don't seem to have wget install, but I do have curl installed. Can you try running these to see if they give errors? Should help us figure out if you have either of them installed and accessible to R:

```
system("wget -h", intern = TRUE)
system("curl -h", intern = TRUE)
```

I suspect both will give errors for you. If so, you could try installing git bash (https://git-scm.com/downloads). I have that on my Windows machine and I think my curl install is coming from there.

**Comment by mpalumbo56** [comment]
I ran the code in R and did produce errors. I tried installing git bash but received the errors again, below. 

> system("wget -h", intern = TRUE) 
Error in system("wget -h", intern = TRUE) : 'wget' not found 
> system("curl -h", intern = TRUE) 
Error in system("curl -h", intern = TRUE) : 'curl' not found
--
 
> | >
>

**Comment by mstrimas** [comment]
ok, I'm at a loss, I'd suggesting reporting this as an issue on the MODIS package repository: https://github.com/MatMatt/MODIS/issues

You can use this simple reproducible example:

```
library(MODIS)
runGdal(product = "MCD12Q1", collection = "006", SDSstring = "01", 
              tileH = 10, tileV = 6,
              begin = "2016.01.01", end = "2016.12.31")
```

I'll keep an eye over there and chime in if necessary. Sorry this is proving to be so complicated, hopefully we can get it sorted out so I can add it to the book and avoid others having the same issues. Thanks!

**Comment by mpalumbo56** [comment]
No worries. I posted it on the MODIS package repository. I'll update the thread if it get sorted out. 
Thanks for the help!

**Comment by mstrimas** [comment]
For future reference, this resource is helpful for getting curl installed on Windows: https://stackoverflow.com/questions/9507353/how-do-i-install-and-use-curl-on-windows
