### ISSUE TITLE
Code missing in 5.4 Prediction (but present in the markdown)

### ISSUE THREAD

**Issue by beausoleilmo** [mstrimas/ebird-best-practices#6]
Perhaps you want to take a look at the line of code in chapter 5 section 4 (5.4)

```
# add to prediction surface
pred_occ <- bind_cols(pred_surface, 
                      occ_prob = occ_pred$fit, 
                      occ_se = occ_pred$se.fit) %>% 

```

as this part

```
  select(latitude, longitude, occ_prob, occ_se)
saveRDS(pred_occ, "output/woothr_occupancy-model_predictions.rds")

```

is missing in the online version. But I was able to see it in the Markdown.

**Comment by mstrimas** [comment]
Thanks for catching this! Working on some updates to Chapter 5 this week and will be sure to correct this.

**Comment by mstrimas** [comment]
should be fixed now
