### ISSUE TITLE
Possible issue with section 3.3

### ISSUE THREAD

**Issue by aeiche01** [mstrimas/ebird-best-practices#7]
I've been working through the code presented in the book and have successfully gotten the MODIS package working. However, I've run into a problem with the code that generates the pland categories, specifically

`lc_extract <- ebird_buff %>% 
  mutate(pland = map2(year_lc, data, calculate_pland, lc = landcover)) %>% 
  select(pland) %>% 
  unnest()
`
I get the following error

` Error in .local(x, ...) : invalid layer names `

Based on the comments in the book suggesting that velox doesn't properly name columns, it seems like there might be an issue with the calculate_pland function immediately prior to this code? It also might specifically be a local problem, but I thought I'd bring it to your attention in case it wasn't.

**Comment by aeiche01** [comment]
Here's the traceback of the error: `21.
stop("invalid layer names") 
20.
.local(x, ...) 
19.
subset(x, i, drop = drop) 
18.
subset(x, i, drop = drop) 
17.
.local(x, i, j, ...) 
16.
lc[[yr]] 
15.
lc[[yr]] at .active-rstudio-document#76
14.
is(x, "RasterLayer") 
13.
velox(lc[[yr]]) at .active-rstudio-document#76
12.
.f(.x[[i]], .y[[i]], ...) 
11.
map2(year_lc, data, calculate_pland, lc = landcover) 
10.
mutate_impl(.data, dots, caller_env()) 
9.
mutate.tbl_df(., pland = map2(year_lc, data, calculate_pland, 
    lc = landcover)) 
8.
mutate(., pland = map2(year_lc, data, calculate_pland, lc = landcover)) 
7.
function_list[[i]](value) 
6.
freduce(value, `_function_list`) 
5.
`_fseq`(`_lhs`) 
4.
eval(quote(`_fseq`(`_lhs`)), env, env) 
3.
eval(quote(`_fseq`(`_lhs`)), env, env) 
2.
withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
1.
ebird_buff %>% mutate(pland = map2(year_lc, data, calculate_pland, 
    lc = landcover)) %>% select(pland) %>% unnest() `

**Comment by aeiche01** [comment]
Okay, I think I figured out the problem. For some reason, the MODIS code provided in the book only downloads up to 2016, even though we include 2017 in the download request. This means that the ebird_buff had layers going up to 2017 (with 2018 included in 2017) but the MODIS files only went up to 2016. I got it to run by adding all years above 2016 into 2016

**Comment by mstrimas** [comment]
Thanks for letting us know! When the book was released 2017 data were available and they're cached on my computer so the code still works. Not sure why they took down the 2017 data, but I will fix the code to account for this this week.

**Comment by mstrimas** [comment]
should be fixed now

**Comment by aeiche01** [comment]
Fantastic!
