### ISSUE TITLE
Possible Issue with prediction-surface.tif

### ISSUE THREAD

**Issue by aeiche01** [mstrimas/ebird-best-practices#8]
It seems like there is a missing WriteRaster() somewhere for prediction-surface.tif. The only time it appears is in section 3.4 `# remove any empty cells at edges
  trim(filename = "data/prediction-surface.tif", overwrite = TRUE)`
However, there is a file called "prediction-surface.tif" in the provided data folder about Wood Thrush (and later commands in the book call to it), which suggests to me that there is supposed to be a writeRaster command in that section that writes the tif.

**Comment by mstrimas** [comment]
By giving a filename argument to `trim()` it should write the results to disk as if you'd called `writeRaster()`. Are you finding that's not the case?

**Comment by aeiche01** [comment]
hmmm yeah it didn't seem to be writing results to a disc. The code successfully ran and didn't show any errors, but the file didn't seem to appear in the data folder afterward

**Comment by mstrimas** [comment]
Strange, it's supposed to... maybe an issue with `raster::trim()`? In any case, I've updated the code to explicitly call `writeRaster()` so this shouldn't be an issue anymore. Thanks for catching this!

**Comment by aeiche01** [comment]
Glad to help!
